import msg = require("./msg");
import okmsg = require("./okmsg");
import ctap = require("./ctap");
import chunk = require("./chunk");
import cbor = require("./cbor");
import ctaphid = require("./ctaphid");
import tunnel = require("./tunnel");
import challenge = require("./challenge");
import bridge = require("./bridge");
export declare let MSG: {
    OKPIN: number;
    OKPINSD: number;
    OKPINSEC: number;
    OKCONNECT: number;
    OKGETLABELS: number;
    OKSETSLOT: number;
    OKWIPESLOT: number;
    OKGETPUBKEY: number;
    OKSIGN: number;
    OKWIPEPRIV: number;
    OKSETPRIV: number;
    OKDECRYPT: number;
    OKRESTORE: number;
    OKGETRESPONSE: number;
    OKPING: number;
    OKFWUPDATE: number;
    OKHMAC: number;
    OKWEBAUTHN: number;
};
export declare let FIELD: {
    LABEL: number;
    USERNAME: number;
    NEXTKEY2: number;
    DELAY2: number;
    PASSWORD: number;
    NEXTKEY3: number;
    DELAY3: number;
    TFATYPE: number;
    TFAUSERNAME: number;
    YUBIAUTH: number;
    LOCKOUT: number;
    WIPEMODE: number;
    TYPESPEED: number;
    KBDLAYOUT: number;
    URL: number;
    NEXTKEY1: number;
    DELAY1: number;
    NEXTKEY4: number;
    NEXTKEY5: number;
    BACKUPKEYMODE: number;
    derivedchallengeMode: number;
    storedchallengeMode: number;
    SECPROFILEMODE: number;
    LEDBRIGHTNESS: number;
    LOCKBUTTON: number;
    hmacchallengeMode: number;
    modkeyMode: number;
    YUBIANDHMAC: number;
};
export declare let IFACE: {
    KEYBOARD: 0;
    FIDO: 1;
    VENDOR: 2;
    SEREMU: 3;
};
export declare let KEYTYPE: {
    NACL: number;
    P256R1: number;
    P256K1: number;
    CURVE25519: number;
};
export declare let KEYACTION: {
    DERIVE_PUBLIC_KEY: number;
    DERIVE_SHARED_SECRET: number;
    DERIVE_PUBLIC_KEY_REQ_PRESS: number;
    DERIVE_SHARED_SECRET_REQ_PRESS: number;
};
export declare let messageId: typeof import("./msg").messageId;
export declare let fieldId: typeof import("./msg").fieldId;
export { msg, okmsg, ctap, chunk, cbor, ctaphid, tunnel, challenge, bridge };
